### ISSUE TITLE
Selector sidebar randomly disappears

### ISSUE THREAD

**Issue by eric-s-raymond** [aidanp/event-scheduler#20]
Under Android 6.01 (Cyanogen 13.0) running chromium-browser the behavior of the seleector sidebar is horribly flaky. Touching it to select or make it scroll often makes it vanish. Often enough to make the scheduler unusable under chromium-browser.

Bug does not reproduce under Firefox.

Looks like what's happening is that chromium-browser sometime forwards touch events to the window under the sidebar.

Recommended fix: Add a toggle to the sidebar that tells the underlying window to ignore touch events.

**Comment by mmpowers** [comment]
A little bit of research indicates that we were using a now-unsupported webkit property.  I tried removing that and explicitly setting a z-order index in the hopes of preventing the event leakage.  I don't have your environment but please let me know if you don't see an improvement.

**Comment by eric-s-raymond** [comment]
Fix confirmed. Nice work, root-causing that so rapidly.

Damn good thing we caught this before WBC. See you there?
