### ISSUE TITLE
2016 Calendar data is out-of-sync

### ISSUE THREAD

**Issue by wcraigtrader** [aidanp/event-scheduler#3]
As the maintainer of the WBC iCalendar data, I update the calendar data fairly frequently in the early days, and then generate data files for the app developers (currently CSV files). I would be happy to generate appropriately formatted files for this project too. Just let me know what formats you need.

I've added a JSON encoding of the detailed schedule data: http://wbc.trader.name/2016/details.json

**Comment by wcraigtrader** [comment]
I've published the WBC iCalendar data for 2017, in case you're interested:

http://trader.name/wbc/2017/

**Comment by mmpowers** [comment]
Now updated to use the 2017 json feed - thanks!
